### ISSUE TITLE
Cannot open it in Microsoft VoTT 2.2.0

### ISSUE THREAD

**Issue by zyberguy** [dipamgoswami/UMID-Urine-Microscopic-Image-Dataset#2]
I have downloaded this dataset and create new project for these images but the annotation are not displayed.
Is there any workaround or how can I import csv file into Microsoft VOTT 2.2.0?

I tried to convert csv to COCO json file from Roboflow and then open it, VoTT says it cannot import version 1.0 file?

**Comment by dipamgoswami** [comment]
Hi,
Sorry for the late reply. 
I am not aware of how to import CSV files into VOTT 2.2.0. I generally prefer using python code for visualizing the boxes. 
Since VOTT cannot import version 1.0 files, maybe try using the older version of VOTT, or maybe it is an issue with the conversion from CSV to JSON files. You can also get some code online to convert CSV to JSON and see if it works that way.
